# Generated by Django 2.2.2 on 2019-06-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alpha2Code', models.CharField(max_length=2)),
                ('capital', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('population', models.IntegerField()),
                ('flag', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
