# Generated by Django 2.2.2 on 2019-06-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='alpha2Code',
            field=models.CharField(max_length=2, verbose_name='ISO2 Country Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=255, verbose_name='Capital City'),
        ),
    ]
